const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",

  GET_POSTS: "GET_POSTS",

  GET_POSTS_PAGE: "GET_POSTS_PAGE",

  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_FAIL: "GET_CATEGORY_FAIL",

  GET_ALL_PRICE: "GET_ALL_PRICE",
  GET_ALL_PRICE_FAIL: "GET_ALL_PRICE_FAIL",

  GET_ALL_AREA: "GET_ALL_AREA",
  GET_ALL_AREA_FAIL: "GET_ALL_AREA_FAIL",

  GET_NEW_POSTS: "GET_NEW_POSTS",
  GET_NEW_POSTS_FAIL: "GET_NEW_POSTS_FAIL",

  GET_ALL_PROVINCES: "GET_ALL_PROVINCES",
  GET_ALL_PROVINCES_FAIL: "GET_ALL_PROVINCES_FAIL",
};
export default actionTypes;
